
import Head from 'next/head'
import Login from '../components/Login'
import UserDashboard from '../components/UserDashboard'
import { useAuth } from '../context/AuthContext'

export default function Home() {
  const { currentUser } = useAuth()
  return (
    < >
    <Head>
      <title>Todos for you</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png" />
    </Head>
    {!currentUser && <Login />}
    {currentUser && <UserDashboard/>}
  </>
  )
}
